# Generated by Django 6.0.5 on 2026-06-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_offering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
