# Generated by Django 6.0.5 on 2026-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('pastor', 'Pastor'), ('assistant_pastor', 'Assistant Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('youth_leader', 'Youth Leader'), ('choir_leader', 'Choir Leader')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
