# Generated by Django 6.0.5 on 2026-06-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_attendance_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('request', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_prayed_for', models.BooleanField(default=False)),
            ],
        ),
    ]
