# Generated by Django 6.0.5 on 2026-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(choices=[('pastor', 'Pastor'), ('teacher', 'Teacher'), ('elder', 'Elder'), ('youth_leader', 'Youth Leader')], max_length=50),
        ),
    ]
