# Generated by Django 6.0.5 on 2026-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
