# Generated by Django 6.0.5 on 2026-06-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_smsmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='title',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='phone',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
