# Generated by Django 6.0.5 on 2026-06-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessage',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
