# Generated by Django 6.0.5 on 2026-06-07 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_created_at_smsmessage_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
